version: "3.9"
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports: ["27017:27017"]
    volumes:
      - mongodata:/data/db

  backend:
    build:
      context: ..
      dockerfile: deployment/docker/backend.Dockerfile
    env_file: ../.env
    depends_on:
      - mongo
      - model
    ports: ["8080:8080"]

  model:
    build:
      context: ..
      dockerfile: deployment/docker/ml.Dockerfile
    depends_on:
      - mongo
    ports: ["8000:8000"]

  frontend:
    build:
      context: ..
      dockerfile: deployment/docker/frontend.Dockerfile
    env_file: ../.env
    depends_on:
      - backend
    ports: ["5173:80"]

volumes:
  mongodata:
